### ISSUE TITLE
Create Listing model for the application

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#1]
Provide an overview of the `Listing` models purpose and how it fits into the project.

- [ ] Define fields for Listing model (#2)
- [ ] Write model fields in models.py (#3)
- [ ] Add validation to the model fields (#4)
- [ ] Create migrations for Listing model (#5)
- [ ] Register Listing model in Django admin (#6)
- [ ] Write unit tests for Listing model (#7)

Related to #23
