### ISSUE TITLE
Create Bid model for the application

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#15]
Provides an overview of the `Bid` models purpose on how it fits into the project.

- [ ] Define fields for Bid model (#16)
- [ ] Write model fields in `models.py` (#17)
- [ ] Add validation to the model fields (#18)
- [ ] Create migrations for Bid model (#21)
- [ ] Register Bid model in Django admin (#19)
- [ ] Write unit tests for Bid model (#20)

Related to #23
