### ISSUE TITLE
Categories page

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#28]
Any user can view this page. Users come here to see a list of categories.

- [x] Categories view (Public) (#30)
- [x] Categories template `categories.html` (Public) (#31)
- [x] Selection of a single category. If done correctly this should be able to just use the `index.html` template without any further editing at this point (Public) (#55 )

Related to #22
