### ISSUE TITLE
Create Category model for the appliaction

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#32]
Provide an overview of the `Category` model's purpose and how it fits into the project.

- [x] Define fields for `Category` model (#33)
- [x] Write model fields in `models.py` (#34)
- [x] Add validation to the model fields (#35)
- [x] Create migrations for `Category` model (#36)
- [x] Register `Category` model in Django admin (#37)
- [x] Write unit tests for `Category` model (#38)

Related to #23
