### ISSUE TITLE
(PRIVATE) Listing details page not author

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#72]
This is the look for the Listing details page when, authed, user is viewing it but they are not the author of the listing.

The authed user should be able to:

- [x] the user should be able to add the item to their “Watchlist” or remove it. (#85 , #86)
- [x] the user should be able to bid on the item. (#90 , #91 , #92)
  - The bid must be at least as large as the starting bid
  - and must be greater than any other bids that have been placed (if any).
  - If the bid doesn’t meet those criteria, the user should be presented with an error.
- [x] If a user is signed in on a closed listing page, and the user has won that auction, the page should say so. (#93)
- [x] Users should be able to add comments to the listing page. (#87 , #88 , #89)

**Comment by webshuriken** [comment]
All the steps in this issue have been addressed and completed.
