### ISSUE TITLE
Create Comment model for the application

### ISSUE THREAD

**Issue by webshuriken** [webshuriken/commerce#8]
Provide an overview of the `Comment` models purpose and how it fits into the project

- [ ] Define fields for Comment model (#9)
- [ ] Write model fields in `models.py` (#10)
- [ ] Add validation to the model fields (#11)
- [ ] Create migrations for Comment model (#12)
- [ ] Register Comment model in Django admin (#13)
- [ ] Write unit tests for Comment model (#14)

Related to #23
